<?php
$test = $block->getTest();
?>
<div class="test-container">
    <form class="test-form" method="post" action=<?php echo $block->getUrl('customizeproduct/manage/save'); ?> data-mage-init='{"validation": {}}'>
        <input type="hidden" name="id" value="<?= $test->getId()?>"/>
        Design Text: <input type="text" name="p_text" class="required-entry" value="<?= $test->getPText(); ?>"/>
        Design Guide: <textarea name="p_d_guide" class="required-entry validate-no-html-tags" rows="10"><?= $test->getPDGuide(); ?></textarea>
        <button type="submit">Submit</button>
    </form>
</div>