<table>
    <tr>
        <th>
            <?= __("Id")?>
        </th>
        <th>
            <?= __("Product Text")?>
        </th>
        <th>
            <?= __("Design Guide")?>
        </th>
        <th>
            <?= __("Edit")?>
        </th>
        <th>
            <?= __("Delete")?>
        </th>
    </tr>
    <?php
    $tests = $block->getTests();

    foreach ($tests as $test) {?>
    <tr>
        <td>
            <?= $test->getId()?>
        </td>
        <td>
            <?= $test->getPText()?>
        </td>
        <td>
            <?= substr($test->getPDGuide(), 0, 20).'...'?>
        </td>
        <td>
            <a href="<?= $block->getUrl('customizeproduct/manage/edit', ['id'=>$test->getId()])?>">
                <?= __('Edit') ?>
            </a>
        </td>
        <td>
            <a href="<?= $block->getUrl('customizeproduct/manage/delete', ['id'=>$test->getId()])?>"
                onclick="return confirm('Are you sure you want to delete this test entry?');">
                <?= __('Delete') ?>
            </a>
        </td>
    </tr>
    <?php } ?>
</table>